# Path where you've got nginx's upload module dumping stuff - needs write access
path_to_uploads: /tmp
# Path to wherever you want FLACs of the uploads archived pre-normalization
path_to_archive: /tmp/archive
# Path to wherever you want the original uploads backing up
path_to_orig_backup: /tmp/orig
# Path to wherever you want the final files exporting to. Playout systems importing from IRIS need access to at least this.
path_to_import: /tmp/import
# Target LRA to use in normalization. LRA is the loudness range factor, as defined by the EBU in technote 3342
# http://tech.ebu.ch/webdav/site/tech/shared/tech/tech3342.pdf
# It's basically how much dynamic range you want to allow in your normalized files. 8 means 16dB/LU of total dynamic range (+-8 from -23LUFS)
# Value of 999 will effectively turn off LRA compression in normalization.
target_lra: 8.0
